### ISSUE TITLE
X-wing is causing an infinite crashing cycle on my world

### ISSUE THREAD

**Issue by ghost** [Parzivail-Modding-Team/GalaxiesParzisStarWarsMod#107]
I was in an X-wing ship, and I save and quit my game, and then wen't back in, and now it's stuck on a crashing loop.
Here is the crash report.

![Screenshot 2024-10-25 170419](https://github.com/user-attachments/assets/3ac5cd7a-5755-4a19-b5aa-362cf1e985da)

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-10-25 16:50:20
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "org.joml.Quaternionfc.x()" because "q" is null
	at knot//org.joml.Quaternionf.set(Quaternionf.java:417)
	at knot//org.joml.Quaternionf.<init>(Quaternionf.java:115)
	at knot//com.parzivail.pswg.entity.ship.ShipEntity.method_5773(ShipEntity.java:287)
	at knot//com.parzivail.pswg.entity.ship.T65BXwing.method_5773(T65BXwing.java:150)
	at knot//net.minecraft.class_638.method_18646(class_638.java:272)
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:480)
	at knot//net.minecraft.class_638.method_32124(class_638.java:255)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
	at knot//net.minecraft.class_638.method_18116(class_638.java:251)
	at knot//net.minecraft.class_310.method_1574(class_310.java:1951)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1237)
	at knot//net.minecraft.class_310.method_1514(class_310.java:856)
	at knot//net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//org.joml.Quaternionf.set(Quaternionf.java:417)
	at knot//org.joml.Quaternionf.<init>(Quaternionf.java:115)
	at knot//com.parzivail.pswg.entity.ship.ShipEntity.method_5773(ShipEntity.java:287)
	at knot//com.parzivail.pswg.entity.ship.T65BXwing.method_5773(T65BXwing.java:150)
	at knot//net.minecraft.class_638.method_18646(class_638.java:272)
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:480)
	at knot//net.minecraft.class_638.method_32124(class_638.java:255)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
	at knot//net.minecraft.class_638.method_18116(class_638.java:251)

-- Entity being ticked --
Details:
	Entity Type: pswg:xwing_t65b (com.parzivail.pswg.entity.ship.T65BXwing)
	Entity ID: 2
	Entity Name: T65B X-Wing
	Entity's Exact location: 60.50, 117.00, 176.50
	Entity's Block location: World: (60,117,176), Section: (at 12,5,0 in 3,7,11; chunk contains blocks 48,-64,176 to 63,319,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: [class_746['SR8TLine'/1, l='ClientLevel', x=58.18, y=117.39, z=178.36]]
	Entity's Vehicle: null
	Entity NBT: {Air:300s,FallDistance:0.0f,Fire:0s,Invulnerable:0b,Motion:[0.0d,0.0d,0.0d],OnGround:0b,PortalCooldown:0,Pos:[60.5d,117.0d,176.5d],Rotation:[-128.74088f,7.496822f],UUID:[I;1305709268,1141263940,-1997756388,-2116537731],cannonState:3b,cockpitAnim:0b,"faux-custom-entity-data:custom":{},rotation:[0.8997739f,-0.06044854f,-0.43141732f,-0.02513944f],throttle:0.0f,wingAnim:0b}
Stacktrace:
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:480)
	at knot//net.minecraft.class_638.method_32124(class_638.java:255)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
	at knot//net.minecraft.class_638.method_18116(class_638.java:251)
	at knot//net.minecraft.class_310.method_1574(class_310.java:1951)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1237)
	at knot//net.minecraft.class_310.method_1514(class_310.java:856)
	at knot//net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['SR8TLine'/1, l='ClientLevel', x=58.18, y=117.39, z=178.36]]
	Chunk stats: 2601, 441
	Level dimension: minecraft:overworld
	Level spawn location: World: (57,114,174), Section: (at 9,2,14 in 3,7,10; chunk contains blocks 48,-64,160 to 63,319,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 256835 game time, 18000 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at knot//net.minecraft.class_638.method_8538(class_638.java:451)
	at knot//net.minecraft.class_310.method_1587(class_310.java:2481)
	at knot//net.minecraft.class_310.method_1514(class_310.java:875)
	at knot//net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/Galaxy UI - 1.20.2 v2.1.zip

-- PSWG Crash Submission Details --
Details:
	Status: 0
	Report ID: 7ec1fc867d9944158366ffebbd6d2672

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2439418408 bytes (2326 MiB) / 3690987520 bytes (3520 MiB) up to 31172067328 bytes (29728 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2070 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e84
	Graphics card #0 versionInfo: DriverVersion=32.0.15.6094
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.40
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.40
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 34765.37
	Virtual memory used (MB): 17163.03
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 37.71
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx29728m -Xms256m
	Fabric Mods: 
		architectury: Architectury 10.1.20
		cloth-config: Cloth Config v12 12.0.137
			cloth-basic-math: cloth-basic-math 0.6.1
		crafttweaker: CraftTweaker 15.0.10
			org_javassist_javassist: javassist 3.29.0-GA
			org_reflections_reflections: reflections 0.10.2
		customstars: Custom Stars 1.2.1+1.20
		fabric-api: Fabric API 0.91.6+1.20.2
			fabric-api-base: Fabric API Base 0.4.33+fce67b32a0
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.43+b1792f7da0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.14+b1792f7da0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.12+73761d2ea0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+73761d2ea0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.43+f4b7e424a0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.4+86b12645a0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.37+f71b366fa0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.16+b1792f7da0
			fabric-commands-v0: Fabric Commands (v0) 0.2.54+df3654b3a0
			fabric-containers-v0: Fabric Containers (v0) 0.1.81+df3654b3a0
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.6+b1792f7da0
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.8+b1792f7da0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.20+f4b7e424a0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.11+b1792f7da0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.57+b1792f7da0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.26+b1792f7da0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.10+b1792f7da0
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.70+df3654b3a0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.42+a44e16a6a0
			fabric-item-api-v1: Fabric Item API (v1) 2.1.33+b1792f7da0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.15+e3d2bf3fa0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.38+f4b7e424a0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.36+df3654b3a0
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.28+c8b10480a0
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.1+3ba460fba0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.2+e3d2bf3fa0
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.56+f4b7e424a0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.6+b1792f7da0
			fabric-models-v0: Fabric Models (v0) 0.4.5+9386d8a7a0
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.5+f4be560ba0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 12.1.2+2ff98d3ba0
			fabric-particles-v1: Fabric Particles (v1) 1.1.4+f4b7e424a0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.14+52b3ebe5a0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.12+b1792f7da0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+2034447ca0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+2034447ca0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.49+df3654b3a0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.39+73761d2ea0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.30+f4b7e424a0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.52+df3654b3a0
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.11+b1792f7da0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.11+239dafd8a0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.12+b1792f7da0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.12+b1792f7da0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.47+b1792f7da0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.14+f4b7e424a0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.13+4944b5a5a0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.3+fce67b32a0
		fabricloader: Fabric Loader 0.16.7
			mixinextras: MixinExtras 0.4.1
		faux-custom-entity-data: Faux-Custom-Entity-Data 7.0.1
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.21
			journeymap-api-fabric: JourneyMap API 1.20.4-1.9-fabric-SNAPSHOT
		minecraft: Minecraft 1.20.2
		modmenu: Mod Menu 8.0.1
		notenoughcrashes: Not Enough Crashes 4.4.7+1.20.2
		origins: Origins 1.12.10
			apoli: Apoli 2.11.11
				additionalentityattributes: Additional Entity Attributes 1.5.0+1.20.2
				calio: Calio 1.13.3
					org_quiltmc_parsers_gson: gson 0.2.1
					org_quiltmc_parsers_json: json 0.2.1
				playerabilitylib: Pal 1.9.0
			reach-entity-attributes: Reach Entity Attributes 2.4.0
		poemofstarwars: Poem o' Star Wars 1.0.1
		pswg: Galaxies: Parzi's Star Wars Mod 0.0.116+1.20.2
			cardinal-components-base: Cardinal Components API (base) 5.3.0
			cardinal-components-entity: Cardinal Components API (entities) 5.3.0
			libzoomer: LibZoomer 0.4.7+1.20
			trinkets: Trinkets 3.8.0
		pswg_addon_clonewars: PSWG Addon: Clone Wars Era 0.0.14
		roughlyenoughitems: Roughly Enough Items 13.1.773
			error_notifier: Error Notifier 1.0.9
		theforce: The Force 0.8
		worldedit: WorldEdit 7.2.17+6544-56d0383
	JVM uptime in seconds: 75.003
	Launched Version: fabric-loader-0.16.7-1.20.2
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 560.94, NVIDIA Corporation
	Window size: 2560x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, file/Galaxy UI - 1.20.2 v2.1.zip
	Current Language: en_us
	Locale: en_US
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['SR8TLine'/1, l='ServerLevel[The Galaxy]', x=58.18, y=117.39, z=178.36]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Galaxies: Parzi's Star Wars Mod (pswg)

**Comment by ghost** [comment]
PSWG Version is BETA.
PSWG Version: pswg-0.0.116+1.20.2
Minecraft Version: 1.20.2
Modloader: Fabric
Fabric Version: fabric-api-0.91.6+1.20.2
OS: Windows 11

**Comment by parzivail** [comment]
Will be fixed in the next release.
