### ISSUE TITLE
Forge 1.7.10 server crash

### ISSUE THREAD

**Issue by Dezzy201** [Parzivail-Modding-Team/GalaxiesParzisStarWarsMod#34]
When starting up the server with the mod installed, it doesn't start, says theres an error and crashes.

1: Install the mod onto the server
2: Start the server
3: Crash

If nothing was wrong, the server would start and players would be able to join with the same jar file and join and have fun!

**Crash Report**
Please insert the crash report here if applicable.
```
Insert Here!
Underneath this text is the crash report.


---- Minecraft Crash Report ----
// Sorry :(

Time: 10/15/19 4:35 PM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.ClassNotFoundException: com.parzivail.swg.StarWarsGalaxy
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: com.parzivail.swg.StarWarsGalaxy
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at cpw.mods.fml.common.ModClassLoader.loadClass(ModClassLoader.java:58)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:440)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 5 more
Caused by: java.lang.UnsupportedClassVersionError: com/parzivail/swg/StarWarsGalaxy : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 33 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 4.15.0-58-generic
	Java Version: 1.7.0_80, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 797095496 bytes (760 MB) / 1029701632 bytes (982 MB) up to 4772069376 bytes (4551 MB)
	JVM Flags: 3 total; -Xms1024M -Xmx5120M -XX:-UsePerfData
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 20 mods loaded, 20 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
	UC	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
	UC	legends{2.3} [Legends Mod] (1Legends-1.7.10-2.3.jar) 
	UC	lightsabers{1.1} [Advanced Lightsabers Mod] (AdvancedLightsabers-1.7.10-1.1.jar) 
	UC	lycanitesmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UC	arcticmobs{1.13.0.5 - MC 1.7.10} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UC	demonmobs{1.13.0.5 - MC 1.7.10} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UC	desertmobs{1.13.0.5 - MC 1.7.10} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UC	forestmobs{1.13.0.5 - MC 1.7.10} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UC	freshwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UC	infernomobs{1.13.0.5 - MC 1.7.10} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UC	junglemobs{1.13.0.5 - MC 1.7.10} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UC	mountainmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UC	plainsmobs{1.13.0.5 - MC 1.7.10} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UC	saltwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UC	shadowmobs{1.13.0.5 - MC 1.7.10} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UC	swampmobs{1.13.0.5 - MC 1.7.10} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UE	pswg{0.0.7} [Galaxies: Parzi's Star Wars Mod] (pswg-0.0.7-1.7.10 (1).jar) 
	UC	worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

Above this text is the crash report.

Screenshot : https://i.imgur.com/ToQkf43.png


 - Mod Version [e.g. 1.3.0]: 'pswg-0.0.7-1.7.10'
 - Minecraft Version [i.e. 1.7.10]: 1.7.10
 - Forge Version [e.g. 10.13.4.1558]: 10.13.4.1448
 - Java Version [e.g. 8]: 8

**Additional context**
I have tried this with all the other parzi star wars mods, they don't work either, but they work fine on singleplayer. I have changed the server version a few times, didn't make a difference.

**Comment by parzivail** [comment]
Despite PSWG moving to 1.12, luckily this looks like it isn't a mod issue.

If you're positive you have Java 8 (aka Java 1.8) installed, make sure that the Java 8 executable is on the PATH and not the executable for Java 7 (i.e. 1.7.0_80, which is what Forge is reporting as the Java version)

There's a good chance it works in singleplayer because whatever launcher you're using is explicitly picking the Java 8 executable and not using the one registered in the PATH.

Run `which java` at the command line and see what it comes up with.

**Comment by Dezzy201** [comment]
And how do I do that? Sorry I don't have alot of knowledge/experience.

**Comment by kb-1000** [comment]
Well, which launcher do you use for Minecraft?

**Comment by parzivail** [comment]
Run `which java` at the command line and post the result here. Should give us a clue as to what Java the game is trying to use.

**Comment by Dezzy201** [comment]
By command line do you mean command promt? If so, its an unknown command. Same on the server console
Sorry if im being really unhelpful or selfish, I do not know what im doing haha.

**Comment by parzivail** [comment]
Yes, I assumed you're running Linux for the server, correct? That's what the log says. `which` should be a valid command on pretty much any Unix-based OS.

**Comment by kb-1000** [comment]
Command prompt? I'd assume you use a Windows client and a linux server, `which` is not a thing on Windows... and ofc you can't access system commands from the server console that just executes them in minecraft

**Comment by Dezzy201** [comment]
I dont think my server is a linux one? Its a hosted server called server.pro which i pay for premium..

**Comment by parzivail** [comment]
Oh, you're paying to have this hosted for you. This is an issue that needs to be taken up with the hosting provider.
