### ISSUE TITLE
Crash when starting server.

### ISSUE THREAD

**Issue by HIGamer07** [Parzivail-Modding-Team/GalaxiesParzisStarWarsMod#38]
When I open my 1.12.2 server this error appears. Does anybody know how to fix it?

`WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore_v1.9.90_mc1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 1/24/20 7:07 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Galaxies: Parzi's Star Wars Mod (pswg)
Caused by: java.lang.NoSuchMethodError: com.parzivail.swg.dimension.tatooine.BiomeTatooine.func_185359_l()Ljava/lang/String;
	at com.parzivail.swg.dimension.tatooine.BiomeTatooine.<init>(BiomeTatooine.java:11)
	at com.parzivail.swg.register.WorldRegister.register(WorldRegister.java:23)
	at com.parzivail.swg.proxy.Common.preInit(Common.java:20)
	at com.parzivail.swg.StarWarsGalaxy.preInit(StarWarsGalaxy.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_231, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2730917776 bytes (2604 MB) / 3755474944 bytes (3581 MB) up to 9544663040 bytes (9102 MB)
	JVM Flags: 2 total; -Xmx10G -Xms2G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 24 mods loaded, 24 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version               | Source                                            | Signature                                |
	|:----- |:----------------- |:--------------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft         | 1.12.2                | minecraft.jar                                     | None                                     |
	| LCH   | mcp               | 9.42                  | minecraft.jar                                     | None                                     |
	| LCH   | FML               | 8.0.99.99             | forge-1.12.2-14.23.5.2847-universal.jar           | None                                     |
	| LCH   | forge             | 14.23.5.2847          | forge-1.12.2-14.23.5.2847-universal.jar           | None                                     |
	| LCH   | creativecoredummy | 1.0.0                 | minecraft.jar                                     | None                                     |
	| LCH   | obfuscate         | 0.2.6                 | minecraft.jar                                     | None                                     |
	| LCH   | bibliocraft       | 2.4.5                 | BiblioCraft[v2.4.5][MC1.12.2].jar                 | None                                     |
	| LCH   | cfm               | 6.3.0                 | cfm-6.3.0-mc1.12.2.jar                            | None                                     |
	| LCH   | chisel            | MC1.12.2-1.0.1.44     | Chisel-MC1.12.2-1.0.1.44.jar                      | None                                     |
	| LCH   | opframe           | 1.4.0                 | OnlinePicFrame_v1.4.33_mc1.12.2.jar               | None                                     |
	| LCH   | creativecore      | 1.9.9                 | CreativeCore_v1.9.90_mc1.12.2.jar                 | None                                     |
	| LCH   | props             | 2.6.3                 | Decocraft-2.6.3_1.12.2.jar                        | None                                     |
	| LCH   | elevatorid        | 1.3.14                | ElevatorMod-1.12.2-1.3.14.jar                     | None                                     |
	| LCH   | fairylights       | 2.1.9                 | fairylights-2.1.9-1.12.2.jar                      | None                                     |
	| LCH   | mts               | 15.9.2                | Immersive+Vehicles-1.12.2-15.9.2 (1).jar          | None                                     |
	| LCH   | malisiscore       | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                      | None                                     |
	| LCH   | malisisdoors      | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                     | None                                     |
	| LCH   | mantle            | 1.12-1.3.3.55         | Mantle-1.12-1.3.3.55.jar                          | None                                     |
	| LCH   | mcwbridges        | 1.0                   | mcw-bridges-1.0.3-mc1.12.2.jar                    | None                                     |
	| LCH   | mtsofficialpack   | 13.0.0                | MTS_Official_Pack_V13.jar                         | None                                     |
	| LCE   | pswg              | 0.0.7-88-gc8712f6     | pswg-1.12.2-0.0.1 (1).jar                         | None                                     |
	| LC    | railcraft         | 12.0.0                | railcraft-12.0.0.jar                              | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LC    | starwars          | 8.9                   | StarWars[1.12.2]-8.9.jar                          | None                                     |
	| LC    | worldedit         | 6.1.10-SNAPSHOT       | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |

	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore_v1.9.90_mc1.12.2.jar)
  
CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  team.chisel.ctm.client.asm.CTMTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)`

**Comment by parzivail** [comment]
Will be fixed in the 1.15 version. I'm not going to close this issue, however, until I can guarantee it's fixed.

**Comment by beetweenlands** [comment]
hello can you please link me the 1.12.2 download if there is one i can't seem to find the downloads

**Comment by parzivail** [comment]
This is defnitely fixed now in the alphas so I'm going to close this now.
