### ISSUE TITLE
Crash while generating a new world

### ISSUE THREAD

**Issue by frikinjay** [Parzivail-Modding-Team/GalaxiesParzisStarWarsMod#55]
On 0.0.54+1.18.1 theres a crash when generating a new world witht the mod present.

```
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1657.method_5854()" because "player" is null
	at com.parzivail.pswg.entity.ship.ShipEntity.getShip(ShipEntity.java:143)
	at com.parzivail.pswg.client.render.camera.CameraHelper.renderWorldHead(CameraHelper.java:63)
	at net.minecraft.class_757.handler$gee000$renderWorldHead(class_757.java:12019)
	at net.minecraft.class_757.method_3188(class_757.java)
	at net.minecraft.class_757.method_3192(class_757.java:811)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	
	Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by parzivail** [comment]
Can you please post the full crash report?

**Comment by frikinjay** [comment]
Let me know if you need the mod list as well.

```Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1657.method_5854()" because "player" is null
	at com.parzivail.pswg.entity.ship.ShipEntity.getShip(ShipEntity.java:143)
	at com.parzivail.pswg.client.render.camera.CameraHelper.renderWorldHead(CameraHelper.java:63)
	at net.minecraft.class_757.handler$gee000$renderWorldHead(class_757.java:12019)
	at net.minecraft.class_757.method_3188(class_757.java)
	at net.minecraft.class_757.method_3192(class_757.java:811)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.parzivail.pswg.entity.ship.ShipEntity.getShip(ShipEntity.java:143)
	at com.parzivail.pswg.client.render.camera.CameraHelper.renderWorldHead(CameraHelper.java:63)
	at net.minecraft.class_757.handler$gee000$renderWorldHead(class_757.java:12019)
	at net.minecraft.class_757.method_3188(class_757.java)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 1024, 389
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,73,256), Section: (at 0,9,0 in -2,4,16; chunk contains blocks -32,-64,256 to -17,319,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 119 game time, 119 day time
	Server brand: ~~ERROR~~ NullPointerException: Cannot invoke "net.minecraft.class_746.method_3135()" because "this.field_3729.field_1724" is null
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, visualoverhaul/coloredwaterbucket, visualoverhaul/fancyfurnace, visualoverhaul/nobrewingbottles, KubeJS Resource Pack [assets]

**Comment by parzivail** [comment]
Yes, the entire log please.
