### ISSUE TITLE
Crash with blasters on 1.18

### ISSUE THREAD

**Issue by frikinjay** [Parzivail-Modding-Team/GalaxiesParzisStarWarsMod#57]
As the title says. While firing the blaster the client crashes.

Crash report:
```
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_634.method_2883(net.minecraft.class_2596)" because the return value of "net.minecraft.class_310.method_1562()" is null
	at com.glisco.conjuring.client.ConjuringClient.lambda$onInitializeClient$4(ConjuringClient.java:73)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$ehf000$onEndTick(net/fabricmc/fabric/mixin/event/lifecycle/client/MinecraftClientMixin.java [fabric-lifecycle-events-v1.mixins.json]:41)
	at net.minecraft.class_310.method_1574(class_310.java:1807)
	at net.minecraft.class_310.method_1523(class_310.java:1086)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.glisco.conjuring.client.ConjuringClient.lambda$onInitializeClient$4(ConjuringClient.java:73)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$ehf000$onEndTick(net/fabricmc/fabric/mixin/event/lifecycle/client/MinecraftClientMixin.java [fabric-lifecycle-events-v1.mixins.json]:41)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2409)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by parzivail** [comment]
This looks like an issue with whatever mod is `com.glisco.conjuring.client.ConjuringClient`. Can you post your full log?

**Comment by frikinjay** [comment]
The mod list is here https://www.curseforge.com/minecraft/modpacks/blocks-from-beyond

**Comment by parzivail** [comment]
I don't think the crash report you originally posted was the one that resulted when you crashed from firing a blaster. Can you recreate the issue and post your full `latest.log`? [Here](https://minecrafthopper.net/help/guides/getting-minecraft-latest-log/) is where to find it.

**Comment by frikinjay** [comment]
https://gist.github.com/frikinjay/db11613c43c7a2e47075a17f3f2d0de9

https://user-images.githubusercontent.com/88995340/155267114-39ff9c28-c4c6-4629-b872-faa7b5d404e8.mp4

**Comment by parzivail** [comment]
Per the video, this issue does not generate a crash on the client if it is being run on a dedicated or internal server. If it was a dedicated server, the server would create a crash report, but singleplayer worlds silently log the issue and kick you from the world.

After some more research, I've determined this is a bug with Create which we have already reported to them. Until Create fixes the issue, you can resolve the problem by removing Create. While the log you uploaded did not seem to contain any mention of the error shown in the video, it did mention Create, which is known to currently cause this issue.

If that does not help, feel free to open another issue.

**Comment by frikinjay** [comment]
This answers my question. Thanks for looking into it.

**Comment by frikinjay** [comment]
Also can you link me to the report so i can keep an eye on when it gets fixed?

**Comment by parzivail** [comment]
We directly reported the crash to TropheusJay on Discord (not GitHub), but this is the commit that resulted from the report:

https://github.com/Fabricators-of-Create/Create/commit/6788389cb221eb9777e121a5e387575b72d6919e

When that commit is integrated into a release, it should be fixed.

**Comment by frikinjay** [comment]
I see, well that works for me.
