### ISSUE TITLE
Crash when trying to spawn in a blaster.

### ISSUE THREAD

**Issue by frikinjay** [Parzivail-Modding-Team/GalaxiesParzisStarWarsMod#62]
Its on quilt loader(0.17.0-beta 2) if that helps. 0.0.71+1.18.2 version of the mod.
```
Description: Getting blaster descriptor

java.lang.NullPointerException: Cannot get blaster descriptor for unknown key "pswg:a280"
	at com.parzivail.pswg.data.SwgBlasterManager.getDataAndAssert(SwgBlasterManager.java:104)
	at com.parzivail.pswg.item.blaster.BlasterItem.getBlasterDescriptor(BlasterItem.java:162)
	at com.parzivail.pswg.item.blaster.BlasterItem.getBlasterDescriptor(BlasterItem.java:155)
	at com.parzivail.pswg.item.blaster.BlasterItem.method_7888(BlasterItem.java:515)
	at net.minecraft.class_1799.method_7917(class_1799.java:528)
	at net.minecraft.class_1661.method_7381(class_1661.java:256)
	at net.minecraft.class_1657.method_6007(class_1657.java:557)
	at net.minecraft.class_1309.method_5773(class_1309.java:2354)
	at net.minecraft.class_1657.method_5773(class_1657.java:275)
	at net.minecraft.class_3222.redirect$jlp000$fixUpdateSuppressionCrashPlayerTick(class_3222.java:26242)
	at net.minecraft.class_3222.method_14226(class_3222.java:478)
	at net.minecraft.class_3244.method_18784(class_3244.java:214)
	at net.minecraft.class_2535.method_10754(class_2535.java:247)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:918)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.handler$jek000$modifiedRunLoop(MinecraftServer.java:15396)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.parzivail.pswg.data.SwgBlasterManager.getDataAndAssert(SwgBlasterManager.java:104)
	at com.parzivail.pswg.item.blaster.BlasterItem.getBlasterDescriptor(BlasterItem.java:162)
	at com.parzivail.pswg.item.blaster.BlasterItem.getBlasterDescriptor(BlasterItem.java:155)
	at com.parzivail.pswg.item.blaster.BlasterItem.method_7888(BlasterItem.java:515)
	at net.minecraft.class_1799.method_7917(class_1799.java:528)
	at net.minecraft.class_1661.method_7381(class_1661.java:256)
	at net.minecraft.class_1657.method_6007(class_1657.java:557)
	at net.minecraft.class_1309.method_5773(class_1309.java:2354)
	at net.minecraft.class_1657.method_5773(class_1657.java:275)
	at net.minecraft.class_3222.redirect$jlp000$fixUpdateSuppressionCrashPlayerTick(class_3222.java:26242)

-- Blaster Manager Data --
Details:
	Defined keys: 
Stacktrace:
	at com.parzivail.pswg.data.SwgBlasterManager.getDataAndAssert(SwgBlasterManager.java:104)
	at com.parzivail.pswg.item.blaster.BlasterItem.getBlasterDescriptor(BlasterItem.java:162)
	at com.parzivail.pswg.item.blaster.BlasterItem.getBlasterDescriptor(BlasterItem.java:155)
	at com.parzivail.pswg.item.blaster.BlasterItem.method_7888(BlasterItem.java:515)
	at net.minecraft.class_1799.method_7917(class_1799.java:528)
	at net.minecraft.class_1661.method_7381(class_1661.java:256)
	at net.minecraft.class_1657.method_6007(class_1657.java:557)
	at net.minecraft.class_1309.method_5773(class_1309.java:2354)
	at net.minecraft.class_1657.method_5773(class_1657.java:275)
	at net.minecraft.class_3222.redirect$jlp000$fixUpdateSuppressionCrashPlayerTick(class_3222.java:26242)
	at net.minecraft.class_3222.method_14226(class_3222.java:478)
	at net.minecraft.class_3244.method_18784(class_3244.java:214)
	at net.minecraft.class_2535.method_10754(class_2535.java:247)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:918)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.handler$jek000$modifiedRunLoop(MinecraftServer.java:15396)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 89
	Entity Name: frikinjay
	Entity's Exact location: 389.96, 117.00, 11115.35
	Entity's Block location: World: (389,117,11115), Section: (at 5,5,11 in 24,7,694; chunk contains blocks 384,0,11104 to 399,255,11119), Region: (0,21; contains chunks 0,672 to 31,703, blocks 0,0,10752 to 511,255,11263)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_3222.method_14226(class_3222.java:478)
	at net.minecraft.class_3244.method_18784(class_3244.java:214)
	at net.minecraft.class_2535.method_10754(class_2535.java:247)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:918)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.handler$jek000$modifiedRunLoop(MinecraftServer.java:15396)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by parzivail** [comment]
We've been somewhat unsuccessfully chasing this crash down. We think it typically happens when entering a world that was generated before the mod was added to the game. The underlying issue is that the server datapack doesn't load blaster data, which has been hard to reproduce. 

* Was this the case in your instance?
* What other mods are installed? 
* Can you reproduce this issue on the same world?
* Can you reproduce this issue on a _new_ world?

**Comment by reverentfeynmen** [comment]
It doesn't do it anymore.
