### ISSUE TITLE
"Incompatible mod sets" when loading on 1.20.1

### ISSUE THREAD

**Issue by flakface** [Parzivail-Modding-Team/GalaxiesParzisStarWarsMod#81]
Using MultiMC as my minecraft launcher.

Installed latest version of fabric 1.14.22, then loaded the latest version of PSWG for 1.20.1.

When mod is disabled, minecraft loads up fine. However, loading in PSWG gives me an immediate Fabric error, stating:

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric-api, version 0.83.1 or later.
	 - Install fabric-api-base, version 0.1.2 or later.
	 - Install fabric, version 0.51.2 or later.
Unmet dependency listing:
	 - Mod 'Galaxies: Parzi's Star Wars Mod' (pswg) 0.0.109+1.20.1 requires version 0.83.1 or later of fabric-api, which is missing!
	 - Mod 'Cardinal Components API (base)' (cardinal-components-base) 5.2.0 requires version 0.1.2 or later of fabric-api-base, which is missing!
	 - Mod 'Cardinal Components API (entities)' (cardinal-components-entity) 5.2.0 requires any version of fabric-api-base, which is missing!
	 - Mod 'Trinkets' (trinkets) 3.7.0 requires version 0.51.2 or later of fabric, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

Is MultiMC the issue? or what could be causing this?

**Comment by kb-1000** [comment]
Install [Fabric API](https://modrinth.com/mod/fabric-api)
