### ISSUE TITLE
Crash -1 when trying to load game

### ISSUE THREAD

**Issue by M1llyM0o** [Parzivail-Modding-Team/GalaxiesParzisStarWarsMod#87]
I'm playing 1.20.1 and I keep receiving this crash msg when I try and load up the game. I've tried both versions of the PSWG mod for 1.20.1 and installed the most recent version of fabric 1.20.1 along with fabric API. I have tried this mod separate from all of my other current mods and I am sure it's an issue with PSWG or something I'm doing wrong.
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'pswg'!

This is the crash report
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2023-11-30 16:58:04
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'pswg'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/loader/impl/entrypoint/EntrypointUtils
	at com.parzivail.pswg.Galaxies.onInitialize(Galaxies.java:163)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383)
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.loader.impl.entrypoint.EntrypointUtils
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 8 more

**Comment by parzivail** [comment]
Can you post your entire crash log? I don't think this is the most recent version of Fabric API.

**Comment by parzivail** [comment]
This is an issue with that particular version of Fabric API. I recommend you update to 1.20.2 with the latest version of everything, or else use Fabric API 0.14.22
